# Port aplikacji
server.port=8081

# Konfiguracja połączenia z PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_db
spring.datasource.username=postgres
spring.datasource.password=P@$$w0rd

# Ustawienia Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Opcjonalne: Formatowanie SQL w konsoli dla lepszej czytelności
spring.jpa.properties.hibernate.format_sql=true