# Podstawowa konfiguracja aplikacji
spring.application.name=bank-api
spring.profiles.default=local
server.port=${SERVER_PORT:8081}

# Ustawienia Hibernate (JPA) + Flyway wspólne dla wszystkich profili
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

# Flyway - wersjonowanie schematu bazy
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

# Opcjonalne: Formatowanie SQL w konsoli dla lepszej czytelności
spring.jpa.properties.hibernate.format_sql=true